### ISSUE TITLE
Do you think we could use different objects? 

### ISSUE THREAD

**Issue by TontonTremblay** [XingruiWang/superclevr-3D-question#1]
Did you try generating data using objaverse for example?

**Comment by XingruiWang** [comment]
Thanks for your interest. Using the larger 3D datasets is an ongoing direction of our project. These 3D models are good resources to expand the dataset, but we need more annotations ( for part especially) to generate questions if follow the same setting of Super-CLEVR-3D.

**Comment by TontonTremblay** [comment]
For sure, the annotation for objaverse is pretty sparse, thank you though, this is very exciting work. I look forward what you guys will be working on next.
